name: Build and Push docker & tutor installed images

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Tutor version to build'
        required: true
        type: string
        default: '20.0.0'

jobs:
  build-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Registry
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: abstract2tech
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

      - name: Build image and push to Docker Hub
        run: |
          docker build --build-arg tutor_release=${{ github.event.inputs.version }} -t abstract2tech/tutor-ci:${{ github.event.inputs.version }} .
          docker push abstract2tech/tutor-ci:${{ github.event.inputs.version }}
